In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/rkiattisak/salaly-prediction-for-beginer/Salary Data.csv

In [2]:
df=pd.read_csv("/kaggle/input/datasets/rkiattisak/salaly-prediction-for-beginer/Salary Data.csv")
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [3]:
df.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    object
 2   Education Level      373 non-null    object
 3   Job Title            373 non-null    object
 4   Years of Experience  373 non-null    float64
 5   Salary               373 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.7+ KB

In [5]:
df.isna().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [6]:
df.dropna(inplace=True)
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [7]:
df=df.rename(columns={"Years of Experience": "Experience"})
df

,Age,Gender,Education Level,Job Title,Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [8]:
X=df[["Experience"]]
X

     Experience
0           5.0
1           3.0
2          15.0
3           7.0
4          20.0
..          ...
370         8.0
371        19.0
372         2.0
373         7.0
374        15.0

[373 rows x 1 columns]

In [9]:
Y=df["Salary"]
Y

0       90000.0
1       65000.0
2      150000.0
3       60000.0
4      200000.0
         ...
370     85000.0
371    170000.0
372     40000.0
373     90000.0
374    150000.0
Name: Salary, Length: 373, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [11]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=45)

In [12]:
model=LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [13]:
prediction=model.predict(X_test)
print(prediction)

[ 93428.20088682  93428.20088682 120737.54793687 182183.57879948
 141219.55822441  52464.18031174 154874.23174943  66118.85383677
 168528.90527446 175356.24203697 100255.53764933  79773.52736179
 154874.23174943  66118.85383677  38809.50678671  42223.17516797
  79773.52736179  52464.18031174  42223.17516797 161701.56851194
 168528.90527446  86600.8641243  127564.88469938  66118.85383677
  52464.18031174  42223.17516797  52464.18031174 113910.21117435
 175356.24203697 154874.23174943  72946.19059928 134392.22146189
 100255.53764933 113910.21117435  45636.84354923  52464.18031174
 175356.24203697 154874.23174943  45636.84354923 182183.57879948
  59291.51707425 141219.55822441 113910.21117435 107082.87441184
 141219.55822441  52464.18031174  79773.52736179 141219.55822441
  52464.18031174 100255.53764933  52464.18031174  66118.85383677
  59291.51707425 175356.24203697  45636.84354923  42223.17516797
 182183.57879948  45636.84354923  66118.85383677 168528.90527446
 120737.54793687  66118.85383677 154874.23174943 161701.56851194
 182183.57879948  42223.17516797  45636.84354923 127564.88469938
  93428.20088682 120737.54793687  86600.8641243   45636.84354923
 175356.24203697 134392.22146189 120737.54793687 100255.53764933
  93428.20088682  79773.52736179 175356.24203697  45636.84354923
  59291.51707425  93428.20088682  66118.85383677  79773.52736179
 161701.56851194 134392.22146189 141219.55822441  66118.85383677
  66118.85383677 182183.57879948  86600.8641243   72946.19059928
  59291.51707425 202665.58908702  59291.51707425  45636.84354923
  52464.18031174  86600.8641243   52464.18031174  72946.19059928
 127564.88469938  86600.8641243   59291.51707425 148046.89498692
  79773.52736179 100255.53764933  86600.8641243   86600.8641243
 168528.90527446  52464.18031174 127564.88469938  79773.52736179]

In [14]:
print(Y_test.shape)
print(prediction.shape)

(112,)
(112,)

In [15]:
acc=r2_score(Y_test,prediction)
print(acc)

0.8653965033399177

*PRACTICAL APPROACH*

In [16]:
X_val=df["Experience"].values
Y_val=df["Salary"].values
m=0
c=0
lr=0.01
epoch=100

In [17]:
n=len(X_val)
costhistory=[]
for epoch_count in range(epoch):
  y_predict=m*X_val+c
  cost=1/n*np.sum((Y_val-y_predict)**2)
  gdm=(-2/n)*np.sum(X_val*(Y_val-y_predict))
  gdc=(-2/n)*np.sum(Y_val-y_predict)
  m=m-(lr*gdm)
  c=c-(lr*gdc)
  costhistory.append(cost)

print("Slope:",m)
print("Intercept:",c)
print("GDM:",gdm)
print("GDC:",gdc)
print(costhistory[-1])

Slope: -2.90902499490187e+31
Intercept: -2.0377153126024047e+30
GDM: 4.4531051185162196e+33
GDC: 3.1193133453756204e+32
3.4548447668229167e+64